spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost:3306/kitchadb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul"
      username: root
      password: dlekqls1121
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
